algoritmo "Calculadora"
// Função Calcular
// Autor : Miguel Silva
// Data : 27/03/2026
var
   A, B, C: real
inicio
Escreval("Digite um valor: ")
Leia (A)
Escreval("Digite outro valor: ")
Leia (B)
C <- A+B
Escreval(" O valor da soma entre: ", A," somado com: ", B, " e: ", C)
C <- A-B
Escreval(" O valor da subtraçao entre: ", A," subtraido com: ", B, " e: ", C)
C <- A*B
Escreval(" O valor da multiplicaçao entre: ", A," multiplicado com: ", B, " e: ", C)
C <- A%B
Escreval(" O valor da divisao entre: ", A," divido com: ", B, " e: ", C)
fimalgoritmo
